baseURL = 'https://www.sirapollokaggwaschools.co.ug/'
languageCode = 'en-us'
title = 'Sir Apollo Kaggwa Schools'
theme = 'saks-theme'
[params]
    mainSchool = true
    defaultDescription = "Sir Apollo Kaggwa Schools are private primary schools registered with the ministry of education and sports with a UNEB centre number offering Education to Ugandan and non-Ugandan children based on the Ugandan Curriculum and equipping them with necessary life skills."
    [params.school]
        motto = 'We Ignite Academic Excellence'
        summary1 = 'Sir Apollo Kaggwa Schools are private primary schools registered with the ministry of education and sports with a UNEB centre number offering Education to Ugandan and non-Ugandan children based on the Ugandan Curriculum and equipping them with necessary life skills.'
        summary2 = 'We provide a stimulating and credible learning environment which will produce dynamic and talented young Ugandan citizens and ensure all learners are equipped to meet the challenges of life”.'
