baseURL = 'https://www.sirapollokaggwaschools.co.ug/'
languageCode = 'en-us'
title = 'Sir Apollo Kaggwa Schools'

[params]
  [params.social]
    email = 'info@sirapollokaggwaschools.co.ug'
    whatsapp = 'https://wa.me/256701195558'
    facebook = 'https://www.facebook.com/SakKitintale'
    twitter = 'https://twitter.com/SirApollo_CPS?s=20'
    youtube = 'https://www.youtube.com/@sirapollokaggwaschools3084?si=EvOVGMKWSkRHu_pv'
