name = 'Theme name'
license = 'MIT'
licenselink = 'https://github.com/owner/repo/LICENSE'
description = 'Theme description'


# Taxonomy terms
tags = ['blog', 'company']
features = ['some', 'awesome', 'features']


# If the theme has a single author
[author]
  name = 'Your name'
  homepage = 'Your website'